### ISSUE TITLE
Task to execute gcloud command line

### ISSUE THREAD

**Issue by gbesancon** [GoogleCloudPlatform/google-cloud-tfs#13]
The credential file is generated while executing the tasks allowing to connect to the appropriate project.
We are currently limited to the pre-defined tasks.
It would be very helpful to have a task allowing to execute any gcloud command (which generate the credential file on the fly) to expand the possibility of this plugin.

**Comment by ILMTitan** [comment]
Thank you for your suggestion. Once I get the go ahead to expand this product, this is the first thing on my list.
