### ISSUE TITLE
Add new Google Cloud Platform connection fails

### ISSUE THREAD

**Issue by kostapetan** [GoogleCloudPlatform/google-cloud-tfs#16]
When I try to add a service endpoint in VSTS, after supplying the required info and JSON key, it fails with the following error message:
<img width="735" alt="screen shot 2017-09-04 at 21 40 48" src="https://user-images.githubusercontent.com/10728102/30037457-358d1466-91bb-11e7-8b94-6e8adbf3bf98.png">
Not sure what else might be relevant info, feel free to reach me to provide more details.

**Comment by ILMTitan** [comment]
I have reproduced this in VSTS, but I can't reproduce it in the latest version of TFS. That is going to make debugging harder.

**Comment by ILMTitan** [comment]
Fix for this is now live. There appears to have been a conflict in the service endpoint name. I changed the name, and updated the major versions of the build tasks. The old version of the tasks "0.\*" will select old endpoints configured before this name conflict occurred. The new version of the tasks "1.\*" will select endpoints created after this fix.
