### ISSUE TITLE
Use release version of the GAE deploy tool

### ISSUE THREAD

**Issue by gbesancon** [GoogleCloudPlatform/google-cloud-tfs#37]
Deployment to GAE currently use by default the beta version of the deploy tool.
It would be better (i guess) to use by default the release version of the tool and have a check box allowing to specify the use of the alpha or beta version when available.

This could be applicable to any other custom tasks.

**Comment by ILMTitan** [comment]
This was fixed in #41.

If a beta command is required, the gcloud build task is always available.
