### ISSUE TITLE
Specify verbosity level of custom task

### ISSUE THREAD

**Issue by gbesancon** [GoogleCloudPlatform/google-cloud-tfs#38]
It would be nice to be able to specify the verbosity level of the custom tasks which is currently info by default.

**Comment by ILMTitan** [comment]
@gbesancon, are you saying you would like a flag to indicate at what level gcloud stdout is sent to (info vs debug)?

**Comment by gbesancon** [comment]
I would think of a drop box with the different levels to populate the  --verbosity="<LEVEL>"

**Comment by ILMTitan** [comment]
As a workaround, you can run `gcloud config set core/verbosity debug` from a Command Line task or the gcloud build task after the Install Google Cloud SDK task.

**Comment by ILMTitan** [comment]
The above workaround will not work for the Deploy GAE task.
