### ISSUE TITLE
VSTS Marketplace version has been removed

### ISSUE THREAD

**Issue by ghost** [GoogleCloudPlatform/google-cloud-tfs#51]
The link in the README is dead and I cannot find the extension by searching the marketplace.

**Comment by ILMTitan** [comment]
Because of the very early nature of this project, it is currently marked as private on the marketplace. We are asking people who want to access the project to sign a trusted tester agreement. I'll get back to you with the contact info of someone who can guide you through the process.

**Comment by ghost** [comment]
Hi.  Thanks for the info. I have quite a few use cases for needing this so I'd be happy to sign the agreement and feedback any testing results I have.

**Comment by ivannaranjo** [comment]
Closing as this seems to be resolved.

**Comment by flobaader** [comment]
Are there any news regarding a public version of the extension? It would also love to use the cloud SDK in our pipeline.

**Comment by constant-wip** [comment]
We need this one. Deploying asp.net core apps in GCP takes a lot of effort.
Are there any ETA? Thanks.

**Comment by iantalarico** [comment]
@flobaader and @projectzerotohero Unfortunately we do not have a current ETA.

**Comment by kedigby** [comment]
I'd be happy to sign up to the trusted tester agreement

**Comment by plfaucher** [comment]
I would also like to sign the trusted tester agreement
