### ISSUE TITLE
Linux / MacOS build agents not supported

### ISSUE THREAD

**Issue by ghost** [GoogleCloudPlatform/google-cloud-tfs#56]
The "Install Google Cloud SDK" build step does not seem supported on non-windows agents.

I have also tested installing the GCloud SDK manually inside a Linux build agent and cannot make the 'kubectl command' step work either.

I am re-testing my steps on the Windows Hosted build agent to confirm it is an issue purely with the OS of the agent.

Can you confirm that only Windows agents are supported?  Otherwise I will be happy to report inside of this ticket any further findings on this.

Also the markdown page https://github.com/GoogleCloudPlatform/google-cloud-tfs/blob/master/DETAILS.md contains a broken link to https://cloud.google.com/tools/cloud-tools-tfs/docs/community

**Comment by iantalarico** [comment]
@ILMTitan This is build step is Windows only right?  Maybe we need to add a note to the docs?

**Comment by ILMTitan** [comment]
The "Install Google Cloud SDK" build step is currently windows only. I will add documentation about that. The next version will have a new build step that works in Linux and MacOS (and is also faster).

**Comment by ILMTitan** [comment]
The new Cloud SDK Tool Installer build step is released, and is compatible with Linux.
