### ISSUE TITLE
Marketplace extension not found

### ISSUE THREAD

**Issue by andyRokit** [GoogleCloudPlatform/google-cloud-tfs#70]
When I follow the marketplace link:

https://marketplace.visualstudio.com/items?itemName=GoogleCloudTools.google-cloud-tfs

I get "We're sorry, the page you requested cannot be found!".  Is there an issue with the current Marketplace item?

**Comment by bddckr** [comment]
#51

**Comment by andyRokit** [comment]
Should this be reflected in the README.md?

**Comment by iantalarico** [comment]
@andyRokit  Yes it should be, the current README lacks these details and is a little confusing.

@ILMTitan Jim can we add some more details to the README to be more explicit about the project being is in alpha and the extension in the marketplace is private?
