### ISSUE TITLE
IS THIS PROJECT DEAD?

### ISSUE THREAD

**Issue by muhaym** [GoogleCloudPlatform/google-cloud-tfs#72]
There are people using Azure Devops Pipeline and Google Cloud. Will there be any releases soon?

**Comment by ILMTitan** [comment]
Unfortunately, there will be no further investment in this project in the foreseeable future.

**Comment by muhaym** [comment]
Can we fix and send PR or release **public version** in Azure Devops

**Comment by ILMTitan** [comment]
I would suggest forking this repository and releasing your own version. It is licensed under the Apache Version 2 license, so you are free to do that.
